// ─────────────────────────────────────────────────────────────
// Shift Handover Report — Round 2 "Reconciliation: Drift Indicator"
//
// Builds an auditable handover document from the drift/reconciliation
// state: the recorded baseline, how the situation drifted, every
// operator decision with its timestamp, and final network health.
// Two outputs, both offline-safe (no external services):
//   · downloadHandoverMarkdown() → .md file download
//   · printHandoverReport()     → printable window (Save as PDF)
// ─────────────────────────────────────────────────────────────

import type {
  BaselineSnapshot,
  DriftReport,
  DriftTimelineEvent,
  ReconciliationItem,
} from '../data/types';

export interface HandoverData {
  baseline: BaselineSnapshot | null;
  report: DriftReport | null;
  timeline: DriftTimelineEvent[];
  reconItems: ReconciliationItem[];
  corridorHistory: Array<{ t: number; score: number }>;
  networkHealth: { efficiency: number; onTimePerf: number; platformUtil: number; signalStatus: string; activeAlerts: number };
}

const fmt = (iso: string) =>
  new Date(iso).toLocaleString('en-IN', { hour12: false, day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit', second: '2-digit' });

export function buildHandoverMarkdown(d: HandoverData): string {
  const now = new Date();
  const lines: string[] = [];
  const resolved = d.reconItems.filter(i => i.status === 'resolved');
  const open = d.reconItems.filter(i => i.status === 'open');
  const scores = d.corridorHistory.map(p => p.score);
  const peak = scores.length ? Math.max(...scores) : 0;

  lines.push('# RailTwin — Shift Handover & Reconciliation Audit');
  lines.push('');
  lines.push(`Generated: ${now.toLocaleString('en-IN', { hour12: false })} IST · RailTwin AI Round 2 (Reconciliation: Drift Indicator)`);
  lines.push('');

  lines.push('## 1 · Recorded context (baseline)');
  if (d.baseline) {
    lines.push(`- **Baseline:** "${d.baseline.name}" (${d.baseline.source})`);
    lines.push(`- **Captured:** ${fmt(d.baseline.capturedAt)}`);
    lines.push(`- **Scope:** ${d.baseline.trains.length} trains, ${Object.keys(d.baseline.weather).length} station forecasts frozen`);
  } else {
    lines.push('- No baseline pinned this shift.');
  }
  lines.push('');

  lines.push('## 2 · Corridor drift summary');
  if (d.report) {
    lines.push(`- **Current corridor drift:** ${Math.round(d.report.corridorScore)}/100 (**${d.report.corridorClass.toUpperCase()}**)`);
    lines.push(`- **Peak drift this shift:** ${Math.round(peak)}/100`);
    lines.push(`- **Baseline age:** ${Math.round(d.report.elapsedMinutes)} min`);
    lines.push('');
    lines.push('| Train | Name | Drift | Class | Δ Delay | Largest contributor |');
    lines.push('|---|---|---|---|---|---|');
    for (const t of d.report.trains) {
      const worst = [...t.components].sort((a, b) => b.weighted - a.weighted)[0];
      lines.push(`| ${t.trainId} | ${t.trainName} | ${Math.round(t.score)}/100 | ${t.driftClass} | ${Math.abs(t.live.delay - t.baseline.delay)} min | ${worst.label} (${worst.weighted} pts) |`);
    }
  } else {
    lines.push('- No drift report available.');
  }
  lines.push('');

  lines.push(`## 3 · Operator reconciliation decisions (${resolved.length})`);
  if (resolved.length === 0) lines.push('- No conflicts were resolved this shift.');
  for (const i of resolved) {
    lines.push(`- **${fmt(i.resolvedAt || i.detectedAt)}** · ${i.type.toUpperCase()} on ${i.entityLabel} (${i.field})`);
    lines.push(`  - ${i.sourceA.name}: ${i.sourceA.value}`);
    lines.push(`  - ${i.sourceB.name}: ${i.sourceB.value}`);
    lines.push(`  - **Decision:** \`${i.resolution}\`${i.similarity !== undefined ? ` · similarity ${Math.round(i.similarity * 100)}%` : ''}`);
  }
  lines.push('');

  lines.push(`## 4 · Open items for the incoming shift (${open.length})`);
  if (open.length === 0) lines.push('- Inbox clear. Nothing pending.');
  for (const i of open) {
    lines.push(`- ${i.type.toUpperCase()} · ${i.entityLabel} (${i.field}) — suggested: \`${i.suggestedResolution}\` — ${i.suggestion}`);
  }
  lines.push('');

  lines.push('## 5 · Drift timeline');
  for (const ev of [...d.timeline].reverse()) {
    lines.push(`- ${fmt(ev.at)} · [${ev.kind}] ${ev.message}`);
  }
  lines.push('');

  lines.push('## 6 · Network health at handover');
  lines.push(`- Efficiency ${d.networkHealth.efficiency}% · On-time ${d.networkHealth.onTimePerf}% · Platform utilisation ${d.networkHealth.platformUtil}% · Signals ${d.networkHealth.signalStatus} · Active alerts ${d.networkHealth.activeAlerts}`);
  lines.push('');
  lines.push('---');
  lines.push('*Drift score = 0.40·schedule + 0.25·position + 0.20·prediction + 0.15·weather (deterministic, passenger-weighted; classes: <15 stable, <40 minor, <70 significant, ≥70 critical). Generated by RailTwin — Team Phantom Coders.*');
  return lines.join('\n');
}

export function downloadHandoverMarkdown(d: HandoverData) {
  const md = buildHandoverMarkdown(d);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  const stamp = new Date().toISOString().slice(0, 16).replace(/[:T]/g, '-');
  a.href = url;
  a.download = `railtwin-shift-handover-${stamp}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Opens a formatted, print-ready window — the browser's Print dialog turns it into a PDF. */
export function printHandoverReport(d: HandoverData) {
  const md = buildHandoverMarkdown(d);
  // Minimal, dependency-free markdown-to-HTML for our own known output shape
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const htmlBody = md.split('\n').map(line => {
    if (line.startsWith('# ')) return `<h1>${esc(line.slice(2))}</h1>`;
    if (line.startsWith('## ')) return `<h2>${esc(line.slice(3))}</h2>`;
    if (line.startsWith('|')) return `<div class="tr">${line.split('|').filter(c => c.trim() !== '').map(c => `<span class="td">${esc(c.trim()).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>')}</span>`).join('')}</div>`;
    if (line.startsWith('  - ')) return `<div class="li sub">${esc(line.slice(4)).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>').replace(/`(.+?)`/g, '<code>$1</code>')}</div>`;
    if (line.startsWith('- ')) return `<div class="li">${esc(line.slice(2)).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>').replace(/`(.+?)`/g, '<code>$1</code>')}</div>`;
    if (line.startsWith('---')) return '<hr/>';
    if (line.startsWith('*') && line.endsWith('*')) return `<p class="foot">${esc(line.slice(1, -1))}</p>`;
    if (line.trim() === '') return '';
    return `<p>${esc(line)}</p>`;
  }).join('\n');

  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) return;
  w.document.write(`<!doctype html><html><head><title>RailTwin Shift Handover</title><style>
    body { font-family: ui-sans-serif, system-ui, sans-serif; color: #111; max-width: 820px; margin: 32px auto; padding: 0 20px; font-size: 13px; line-height: 1.55; }
    h1 { font-size: 22px; border-bottom: 3px solid #2563eb; padding-bottom: 8px; }
    h2 { font-size: 15px; margin-top: 22px; color: #1e3a8a; }
    .li { margin: 3px 0 3px 14px; }
    .li.sub { margin-left: 34px; color: #444; }
    .tr { display: flex; border-bottom: 1px solid #e5e7eb; padding: 3px 0; }
    .tr:first-of-type { font-weight: 700; }
    .td { flex: 1; padding: 0 6px; font-size: 12px; }
    code { background: #f1f5f9; border: 1px solid #e2e8f0; border-radius: 4px; padding: 0 4px; font-size: 11px; }
    .foot { color: #64748b; font-size: 11px; font-style: italic; }
    hr { border: none; border-top: 1px solid #cbd5e1; margin: 18px 0; }
    @media print { body { margin: 10mm; } }
  </style></head><body>${htmlBody}<script>setTimeout(() => window.print(), 400);</script></body></html>`);
  w.document.close();
}
